### ISSUE TITLE
How to control devices that don't support LAN API

### ISSUE THREAD

**Issue by xXMrJackXx** [wez/govee2mqtt#26]
Hi there!

I have some devices that support LAN API and they work great with govee2mqtt!
But I also have a device that is not on the support list (Dreamview T1, H6199).
govee2mqtt lists the device in the log:
```
[2024-01-07T17:15:58 INFO  govee::commands::serve] DreamView T1 sku=H6199
[2024-01-07T17:15:58 INFO  govee::commands::serve]   Platform API: devices.types.light. supports_rgb=true supports_brightness=true
[2024-01-07T17:15:58 INFO  govee::commands::serve]                 color_temp=Some((2000, 9000)) segment_rgb=Some(0..15)
[2024-01-07T17:15:58 INFO  govee::commands::serve]   Undoc: room=None supports_iot=true ble_only=true
```

But it does not show up in my MQTT broker. Is this intended, and if yes: What's the best way to control such devices? Use the official Home Assistant plugin?

**Comment by wez** [comment]
Hmm the `ble_only=true` part there means that govee2mqtt thinks that the device can only be controlled via bluetooth.
Is that true?  It makes that determination from the govee APIs based on the wifiName being blank.

If that device is legitimately BLE only: There's no BLE support in govee2mqtt at this time and I'm not sure if I want to add it; I did look at it when building it originally, but I found that discovering devices from my workstation was slow and error prone, and since all of my devices are wifi capable, it didn't seem worth the frustration.

If it does have working wifi, then something is wonky in the data.
If you go to the `Govee to MQTT` device in the MQTT integration, there is a Purge Caches button. Press it once and it should clear the caches and re-register your devices.

I'd be interested to see what's in the logs for the addon after clicking that.

**Comment by xXMrJackXx** [comment]
The Dreamview also works over WIFI, so it's not bluetooth only. I disabled bluetooth on my smartphone and it shows the wifi symbol next to the device, and it also can be controlled.

After purging the cache, there was no automatic re-registering so I manually restarted the docker container. The log shows the same as before.

**Comment by wez** [comment]
Please set the debug level to `govee::commands::serve=trace,info` and restart the container. If you're using the addon, you do that via the addon UI.  If you are running the docker container yourself, you can set `RUST_LOG=govee::commands::serve=trace,info` in its environment.

That will capture the metadata returned from both the platform API and the undocumented API for this device; please put it into a `.txt` file and attach it to this issue.

**Note: I'd recommend redacting the `topic` and `secret_code` fields from the output. I'm not sure what a bad actor could do with that information without also having your credentials, but it just feels prudent to avoid sharing it in public.**

**Comment by xXMrJackXx** [comment]
Hm, before I post the log file: I just looked through it and remembered your comment about the blank ``wifi_name``.
Maybe I should note that the device that isn't shown is on a different VLAN. Could it have something to do with the fact that the integration thinks it's just bluetooth only?
I'll try to move it to the same subnet as the other lights.

**Comment by xXMrJackXx** [comment]
Yes, that' it! I moved it to the other VLAN and now it shows up!

**Comment by wez** [comment]
`GOVEE_LAN_SCAN` is intended to make it easier to deal with this sort of network topology, yes.
https://github.com/wez/govee2mqtt/blob/main/docs/LAN.md has more information.
